apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:9.4
        name: db
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: data-01
      volumes:
      - name: postgres-storage
        gcePersistentDisk:
          fsType: ext4
          # This GCE PD must already exist -
          # see https://kubernetes.io/docs/concepts/storage/volumes/#gcepersistentdisk
          pdName: example-disk
